on:
  pull_request:
    branches:
      - master
  push:
    branches:
      -master

jobs:
  test-compose-action:
    runs-on: ubuntu-latest
    name: Flutter Android Action
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle

